require:
  - rubocop-performance
  - rubocop-rspec
  
AllCops:
  TargetRubyVersion: 2.7.3
  Exclude:
    - 'vendor/bundle/**/*'
  NewCops: enable

Layout/LineLength:
  Max: 120

Style/Documentation:
  Enabled: false

Style/HashSyntax:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'codebreaker.gemspec'
  IgnoredMethods: ['describe', 'context']

RSpec/MultipleMemoizedHelpers:
  Enabled: False
